version: '2'
services:
  app:
    image: 'easyfix:latest'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/easyfix
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=NoviStudentLogin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    build:
      context: .
    container_name: app
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres